/*
 * AviApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.66
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.ts';
import CustomerDto from './model/CustomerDto';
import LoginRequestDto from './model/LoginRequestDto';
import MenuItemDto from './model/MenuItemDto';
import OrderDto from './model/OrderDto';
import OrderMenuItemDto from './model/OrderMenuItemDto';
import RoleDto from './model/RoleDto';
import UserDto from './model/UserDto';
import AuthApi from './Api/tsfiles/AuthApi.js';
import CustomerApi from './api/CustomerApi';
import MenuItemApi from './api/MenuItemApi';
import OrderApi from './api/OrderApi';
import RolesApi from './api/RolesApi';
import UserApi from './Api/UserApi.js';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AviApp = require('index'); // See note below*.
* var xxxSvc = new AviApp.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AviApp.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AviApp.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AviApp.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CustomerDto model constructor.
     * @property {module:model/CustomerDto}
     */
    CustomerDto,

    /**
     * The LoginRequestDto model constructor.
     * @property {module:model/LoginRequestDto}
     */
    LoginRequestDto,

    /**
     * The MenuItemDto model constructor.
     * @property {module:model/MenuItemDto}
     */
    MenuItemDto,

    /**
     * The OrderDto model constructor.
     * @property {module:model/OrderDto}
     */
    OrderDto,

    /**
     * The OrderMenuItemDto model constructor.
     * @property {module:model/OrderMenuItemDto}
     */
    OrderMenuItemDto,

    /**
     * The RoleDto model constructor.
     * @property {module:model/RoleDto}
     */
    RoleDto,

    /**
     * The UserDto model constructor.
     * @property {module:model/UserDto}
     */
    UserDto,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The CustomerApi service constructor.
    * @property {module:api/CustomerApi}
    */
    CustomerApi,

    /**
    * The MenuItemApi service constructor.
    * @property {module:api/MenuItemApi}
    */
    MenuItemApi,

    /**
    * The OrderApi service constructor.
    * @property {module:api/OrderApi}
    */
    OrderApi,

    /**
    * The RolesApi service constructor.
    * @property {module:api/RolesApi}
    */
    RolesApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
